services:
  - type: web
    name: projectscope-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_DB
        sync: false
      - key: MYSQL_PORT
        value: "3306"